/* This file was automatically generated. DO NOT UPDATE MANUALLY. */
import * as stylex from "@stylexjs/stylex";

export const colors = stylex.defineConsts({
  white: "var(--mantine-color-white)",
  black: "var(--mantine-color-black)",
  text: "var(--mantine-color-text)",
  body: "var(--mantine-color-body)",
  error: "var(--mantine-color-error)",
  placeholder: "var(--mantine-color-placeholder)",
  anchor: "var(--mantine-color-anchor)",
  default: "var(--mantine-color-default)",
  defaultHover: "var(--mantine-color-default-hover)",
  defaultColor: "var(--mantine-color-default-color)",
  defaultBorder: "var(--mantine-color-default-border)",
  dimmed: "var(--mantine-color-dimmed)",
  disabledBody: "var(--mantine-color-disabled)",
  disabledText: "var(--mantine-color-disabled-color)",
  disabledBorder: "var(--mantine-color-disabled-border)",
  primary_0: "var(--mantine-primary-color-0)",
  primary_1: "var(--mantine-primary-color-1)",
  primary_2: "var(--mantine-primary-color-2)",
  primary_3: "var(--mantine-primary-color-3)",
  primary_4: "var(--mantine-primary-color-4)",
  primary_5: "var(--mantine-primary-color-5)",
  primary_6: "var(--mantine-primary-color-6)",
  primary_7: "var(--mantine-primary-color-7)",
  primary_8: "var(--mantine-primary-color-8)",
  primary_9: "var(--mantine-primary-color-9)",
  primaryText: "var(--mantine-primary-color-filled)",
  primaryFilled: "var(--mantine-primary-color-filled)",
  primaryFilledHover: "var(--mantine-primary-color-filled-hover)",
  primaryLight: "var(--mantine-primary-color-light)",
  primaryLightHover: "var(--mantine-primary-color-light-hover)",
  primaryLightColor: "var(--mantine-primary-color-light-color)",
  primaryOutline: "var(--mantine-primary-color-outline)",
  primaryOutlineHover: "var(--mantine-primary-color-outline-hover)",
  dark_0: "var(--mantine-color-dark-0)",
  dark_1: "var(--mantine-color-dark-1)",
  dark_2: "var(--mantine-color-dark-2)",
  dark_3: "var(--mantine-color-dark-3)",
  dark_4: "var(--mantine-color-dark-4)",
  dark_5: "var(--mantine-color-dark-5)",
  dark_6: "var(--mantine-color-dark-6)",
  dark_7: "var(--mantine-color-dark-7)",
  dark_8: "var(--mantine-color-dark-8)",
  dark_9: "var(--mantine-color-dark-9)",
  darkText: "var(--mantine-color-dark-filled)",
  darkFilled: "var(--mantine-color-dark-filled)",
  darkFilledHover: "var(--mantine-color-dark-filled-hover)",
  darkLight: "var(--mantine-color-dark-light)",
  darkLightHover: "var(--mantine-color-dark-light-hover)",
  darkLightColor: "var(--mantine-color-dark-light-color)",
  darkOutline: "var(--mantine-color-dark-outline)",
  darkOutlineHover: "var(--mantine-color-dark-outline-hover)",
  gray_0: "var(--mantine-color-gray-0)",
  gray_1: "var(--mantine-color-gray-1)",
  gray_2: "var(--mantine-color-gray-2)",
  gray_3: "var(--mantine-color-gray-3)",
  gray_4: "var(--mantine-color-gray-4)",
  gray_5: "var(--mantine-color-gray-5)",
  gray_6: "var(--mantine-color-gray-6)",
  gray_7: "var(--mantine-color-gray-7)",
  gray_8: "var(--mantine-color-gray-8)",
  gray_9: "var(--mantine-color-gray-9)",
  grayText: "var(--mantine-color-gray-filled)",
  grayFilled: "var(--mantine-color-gray-filled)",
  grayFilledHover: "var(--mantine-color-gray-filled-hover)",
  grayLight: "var(--mantine-color-gray-light)",
  grayLightHover: "var(--mantine-color-gray-light-hover)",
  grayLightColor: "var(--mantine-color-gray-light-color)",
  grayOutline: "var(--mantine-color-gray-outline)",
  grayOutlineHover: "var(--mantine-color-gray-outline-hover)",
  red_0: "var(--mantine-color-red-0)",
  red_1: "var(--mantine-color-red-1)",
  red_2: "var(--mantine-color-red-2)",
  red_3: "var(--mantine-color-red-3)",
  red_4: "var(--mantine-color-red-4)",
  red_5: "var(--mantine-color-red-5)",
  red_6: "var(--mantine-color-red-6)",
  red_7: "var(--mantine-color-red-7)",
  red_8: "var(--mantine-color-red-8)",
  red_9: "var(--mantine-color-red-9)",
  redText: "var(--mantine-color-red-filled)",
  redFilled: "var(--mantine-color-red-filled)",
  redFilledHover: "var(--mantine-color-red-filled-hover)",
  redLight: "var(--mantine-color-red-light)",
  redLightHover: "var(--mantine-color-red-light-hover)",
  redLightColor: "var(--mantine-color-red-light-color)",
  redOutline: "var(--mantine-color-red-outline)",
  redOutlineHover: "var(--mantine-color-red-outline-hover)",
  pink_0: "var(--mantine-color-pink-0)",
  pink_1: "var(--mantine-color-pink-1)",
  pink_2: "var(--mantine-color-pink-2)",
  pink_3: "var(--mantine-color-pink-3)",
  pink_4: "var(--mantine-color-pink-4)",
  pink_5: "var(--mantine-color-pink-5)",
  pink_6: "var(--mantine-color-pink-6)",
  pink_7: "var(--mantine-color-pink-7)",
  pink_8: "var(--mantine-color-pink-8)",
  pink_9: "var(--mantine-color-pink-9)",
  pinkText: "var(--mantine-color-pink-filled)",
  pinkFilled: "var(--mantine-color-pink-filled)",
  pinkFilledHover: "var(--mantine-color-pink-filled-hover)",
  pinkLight: "var(--mantine-color-pink-light)",
  pinkLightHover: "var(--mantine-color-pink-light-hover)",
  pinkLightColor: "var(--mantine-color-pink-light-color)",
  pinkOutline: "var(--mantine-color-pink-outline)",
  pinkOutlineHover: "var(--mantine-color-pink-outline-hover)",
  grape_0: "var(--mantine-color-grape-0)",
  grape_1: "var(--mantine-color-grape-1)",
  grape_2: "var(--mantine-color-grape-2)",
  grape_3: "var(--mantine-color-grape-3)",
  grape_4: "var(--mantine-color-grape-4)",
  grape_5: "var(--mantine-color-grape-5)",
  grape_6: "var(--mantine-color-grape-6)",
  grape_7: "var(--mantine-color-grape-7)",
  grape_8: "var(--mantine-color-grape-8)",
  grape_9: "var(--mantine-color-grape-9)",
  grapeText: "var(--mantine-color-grape-filled)",
  grapeFilled: "var(--mantine-color-grape-filled)",
  grapeFilledHover: "var(--mantine-color-grape-filled-hover)",
  grapeLight: "var(--mantine-color-grape-light)",
  grapeLightHover: "var(--mantine-color-grape-light-hover)",
  grapeLightColor: "var(--mantine-color-grape-light-color)",
  grapeOutline: "var(--mantine-color-grape-outline)",
  grapeOutlineHover: "var(--mantine-color-grape-outline-hover)",
  violet_0: "var(--mantine-color-violet-0)",
  violet_1: "var(--mantine-color-violet-1)",
  violet_2: "var(--mantine-color-violet-2)",
  violet_3: "var(--mantine-color-violet-3)",
  violet_4: "var(--mantine-color-violet-4)",
  violet_5: "var(--mantine-color-violet-5)",
  violet_6: "var(--mantine-color-violet-6)",
  violet_7: "var(--mantine-color-violet-7)",
  violet_8: "var(--mantine-color-violet-8)",
  violet_9: "var(--mantine-color-violet-9)",
  violetText: "var(--mantine-color-violet-filled)",
  violetFilled: "var(--mantine-color-violet-filled)",
  violetFilledHover: "var(--mantine-color-violet-filled-hover)",
  violetLight: "var(--mantine-color-violet-light)",
  violetLightHover: "var(--mantine-color-violet-light-hover)",
  violetLightColor: "var(--mantine-color-violet-light-color)",
  violetOutline: "var(--mantine-color-violet-outline)",
  violetOutlineHover: "var(--mantine-color-violet-outline-hover)",
  indigo_0: "var(--mantine-color-indigo-0)",
  indigo_1: "var(--mantine-color-indigo-1)",
  indigo_2: "var(--mantine-color-indigo-2)",
  indigo_3: "var(--mantine-color-indigo-3)",
  indigo_4: "var(--mantine-color-indigo-4)",
  indigo_5: "var(--mantine-color-indigo-5)",
  indigo_6: "var(--mantine-color-indigo-6)",
  indigo_7: "var(--mantine-color-indigo-7)",
  indigo_8: "var(--mantine-color-indigo-8)",
  indigo_9: "var(--mantine-color-indigo-9)",
  indigoText: "var(--mantine-color-indigo-filled)",
  indigoFilled: "var(--mantine-color-indigo-filled)",
  indigoFilledHover: "var(--mantine-color-indigo-filled-hover)",
  indigoLight: "var(--mantine-color-indigo-light)",
  indigoLightHover: "var(--mantine-color-indigo-light-hover)",
  indigoLightColor: "var(--mantine-color-indigo-light-color)",
  indigoOutline: "var(--mantine-color-indigo-outline)",
  indigoOutlineHover: "var(--mantine-color-indigo-outline-hover)",
  blue_0: "var(--mantine-color-blue-0)",
  blue_1: "var(--mantine-color-blue-1)",
  blue_2: "var(--mantine-color-blue-2)",
  blue_3: "var(--mantine-color-blue-3)",
  blue_4: "var(--mantine-color-blue-4)",
  blue_5: "var(--mantine-color-blue-5)",
  blue_6: "var(--mantine-color-blue-6)",
  blue_7: "var(--mantine-color-blue-7)",
  blue_8: "var(--mantine-color-blue-8)",
  blue_9: "var(--mantine-color-blue-9)",
  blueText: "var(--mantine-color-blue-filled)",
  blueFilled: "var(--mantine-color-blue-filled)",
  blueFilledHover: "var(--mantine-color-blue-filled-hover)",
  blueLight: "var(--mantine-color-blue-light)",
  blueLightHover: "var(--mantine-color-blue-light-hover)",
  blueLightColor: "var(--mantine-color-blue-light-color)",
  blueOutline: "var(--mantine-color-blue-outline)",
  blueOutlineHover: "var(--mantine-color-blue-outline-hover)",
  cyan_0: "var(--mantine-color-cyan-0)",
  cyan_1: "var(--mantine-color-cyan-1)",
  cyan_2: "var(--mantine-color-cyan-2)",
  cyan_3: "var(--mantine-color-cyan-3)",
  cyan_4: "var(--mantine-color-cyan-4)",
  cyan_5: "var(--mantine-color-cyan-5)",
  cyan_6: "var(--mantine-color-cyan-6)",
  cyan_7: "var(--mantine-color-cyan-7)",
  cyan_8: "var(--mantine-color-cyan-8)",
  cyan_9: "var(--mantine-color-cyan-9)",
  cyanText: "var(--mantine-color-cyan-filled)",
  cyanFilled: "var(--mantine-color-cyan-filled)",
  cyanFilledHover: "var(--mantine-color-cyan-filled-hover)",
  cyanLight: "var(--mantine-color-cyan-light)",
  cyanLightHover: "var(--mantine-color-cyan-light-hover)",
  cyanLightColor: "var(--mantine-color-cyan-light-color)",
  cyanOutline: "var(--mantine-color-cyan-outline)",
  cyanOutlineHover: "var(--mantine-color-cyan-outline-hover)",
  teal_0: "var(--mantine-color-teal-0)",
  teal_1: "var(--mantine-color-teal-1)",
  teal_2: "var(--mantine-color-teal-2)",
  teal_3: "var(--mantine-color-teal-3)",
  teal_4: "var(--mantine-color-teal-4)",
  teal_5: "var(--mantine-color-teal-5)",
  teal_6: "var(--mantine-color-teal-6)",
  teal_7: "var(--mantine-color-teal-7)",
  teal_8: "var(--mantine-color-teal-8)",
  teal_9: "var(--mantine-color-teal-9)",
  tealText: "var(--mantine-color-teal-filled)",
  tealFilled: "var(--mantine-color-teal-filled)",
  tealFilledHover: "var(--mantine-color-teal-filled-hover)",
  tealLight: "var(--mantine-color-teal-light)",
  tealLightHover: "var(--mantine-color-teal-light-hover)",
  tealLightColor: "var(--mantine-color-teal-light-color)",
  tealOutline: "var(--mantine-color-teal-outline)",
  tealOutlineHover: "var(--mantine-color-teal-outline-hover)",
  green_0: "var(--mantine-color-green-0)",
  green_1: "var(--mantine-color-green-1)",
  green_2: "var(--mantine-color-green-2)",
  green_3: "var(--mantine-color-green-3)",
  green_4: "var(--mantine-color-green-4)",
  green_5: "var(--mantine-color-green-5)",
  green_6: "var(--mantine-color-green-6)",
  green_7: "var(--mantine-color-green-7)",
  green_8: "var(--mantine-color-green-8)",
  green_9: "var(--mantine-color-green-9)",
  greenText: "var(--mantine-color-green-filled)",
  greenFilled: "var(--mantine-color-green-filled)",
  greenFilledHover: "var(--mantine-color-green-filled-hover)",
  greenLight: "var(--mantine-color-green-light)",
  greenLightHover: "var(--mantine-color-green-light-hover)",
  greenLightColor: "var(--mantine-color-green-light-color)",
  greenOutline: "var(--mantine-color-green-outline)",
  greenOutlineHover: "var(--mantine-color-green-outline-hover)",
  lime_0: "var(--mantine-color-lime-0)",
  lime_1: "var(--mantine-color-lime-1)",
  lime_2: "var(--mantine-color-lime-2)",
  lime_3: "var(--mantine-color-lime-3)",
  lime_4: "var(--mantine-color-lime-4)",
  lime_5: "var(--mantine-color-lime-5)",
  lime_6: "var(--mantine-color-lime-6)",
  lime_7: "var(--mantine-color-lime-7)",
  lime_8: "var(--mantine-color-lime-8)",
  lime_9: "var(--mantine-color-lime-9)",
  limeText: "var(--mantine-color-lime-filled)",
  limeFilled: "var(--mantine-color-lime-filled)",
  limeFilledHover: "var(--mantine-color-lime-filled-hover)",
  limeLight: "var(--mantine-color-lime-light)",
  limeLightHover: "var(--mantine-color-lime-light-hover)",
  limeLightColor: "var(--mantine-color-lime-light-color)",
  limeOutline: "var(--mantine-color-lime-outline)",
  limeOutlineHover: "var(--mantine-color-lime-outline-hover)",
  yellow_0: "var(--mantine-color-yellow-0)",
  yellow_1: "var(--mantine-color-yellow-1)",
  yellow_2: "var(--mantine-color-yellow-2)",
  yellow_3: "var(--mantine-color-yellow-3)",
  yellow_4: "var(--mantine-color-yellow-4)",
  yellow_5: "var(--mantine-color-yellow-5)",
  yellow_6: "var(--mantine-color-yellow-6)",
  yellow_7: "var(--mantine-color-yellow-7)",
  yellow_8: "var(--mantine-color-yellow-8)",
  yellow_9: "var(--mantine-color-yellow-9)",
  yellowText: "var(--mantine-color-yellow-filled)",
  yellowFilled: "var(--mantine-color-yellow-filled)",
  yellowFilledHover: "var(--mantine-color-yellow-filled-hover)",
  yellowLight: "var(--mantine-color-yellow-light)",
  yellowLightHover: "var(--mantine-color-yellow-light-hover)",
  yellowLightColor: "var(--mantine-color-yellow-light-color)",
  yellowOutline: "var(--mantine-color-yellow-outline)",
  yellowOutlineHover: "var(--mantine-color-yellow-outline-hover)",
  orange_0: "var(--mantine-color-orange-0)",
  orange_1: "var(--mantine-color-orange-1)",
  orange_2: "var(--mantine-color-orange-2)",
  orange_3: "var(--mantine-color-orange-3)",
  orange_4: "var(--mantine-color-orange-4)",
  orange_5: "var(--mantine-color-orange-5)",
  orange_6: "var(--mantine-color-orange-6)",
  orange_7: "var(--mantine-color-orange-7)",
  orange_8: "var(--mantine-color-orange-8)",
  orange_9: "var(--mantine-color-orange-9)",
  orangeText: "var(--mantine-color-orange-filled)",
  orangeFilled: "var(--mantine-color-orange-filled)",
  orangeFilledHover: "var(--mantine-color-orange-filled-hover)",
  orangeLight: "var(--mantine-color-orange-light)",
  orangeLightHover: "var(--mantine-color-orange-light-hover)",
  orangeLightColor: "var(--mantine-color-orange-light-color)",
  orangeOutline: "var(--mantine-color-orange-outline)",
  orangeOutlineHover: "var(--mantine-color-orange-outline-hover)",
});

export const breakpoints = stylex.defineConsts({
  xs: "var(--mantine-breakpoint-xs)",
  sm: "var(--mantine-breakpoint-sm)",
  md: "var(--mantine-breakpoint-md)",
  lg: "var(--mantine-breakpoint-lg)",
  xl: "var(--mantine-breakpoint-xl)",
});

export const spacing = stylex.defineConsts({
  xs: "var(--mantine-spacing-xs)",
  sm: "var(--mantine-spacing-sm)",
  md: "var(--mantine-spacing-md)",
  lg: "var(--mantine-spacing-lg)",
  xl: "var(--mantine-spacing-xl)",
});

export const fontSizes = stylex.defineConsts({
  xs: "var(--mantine-font-size-xs)",
  sm: "var(--mantine-font-size-sm)",
  md: "var(--mantine-font-size-md)",
  lg: "var(--mantine-font-size-lg)",
  xl: "var(--mantine-font-size-xl)",
});

export const lineHeights = stylex.defineConsts({
  xs: "var(--mantine-line-height-xs)",
  sm: "var(--mantine-line-height-sm)",
  md: "var(--mantine-line-height-md)",
  lg: "var(--mantine-line-height-lg)",
  xl: "var(--mantine-line-height-xl)",
});

export const shadows = stylex.defineConsts({
  xs: "var(--mantine-shadow-xs)",
  sm: "var(--mantine-shadow-sm)",
  md: "var(--mantine-shadow-md)",
  lg: "var(--mantine-shadow-lg)",
  xl: "var(--mantine-shadow-xl)",
});

export const radius = stylex.defineConsts({
  xs: "var(--mantine-radius-xs)",
  sm: "var(--mantine-radius-sm)",
  md: "var(--mantine-radius-md)",
  lg: "var(--mantine-radius-lg)",
  xl: "var(--mantine-radius-xl)",
});

export const headings = stylex.defineConsts({
  h1_fontSize: "var(--mantine-h1-font-size)",
  h1_lineHeight: "var(--mantine-h1-line-height)",
  h1_fontWeight: "var(--mantine-h1-font-weight)",
  h2_fontSize: "var(--mantine-h2-font-size)",
  h2_lineHeight: "var(--mantine-h2-line-height)",
  h2_fontWeight: "var(--mantine-h2-font-weight)",
  h3_fontSize: "var(--mantine-h3-font-size)",
  h3_lineHeight: "var(--mantine-h3-line-height)",
  h3_fontWeight: "var(--mantine-h3-font-weight)",
  h4_fontSize: "var(--mantine-h4-font-size)",
  h4_lineHeight: "var(--mantine-h4-line-height)",
  h4_fontWeight: "var(--mantine-h4-font-weight)",
  h5_fontSize: "var(--mantine-h5-font-size)",
  h5_lineHeight: "var(--mantine-h5-line-height)",
  h5_fontWeight: "var(--mantine-h5-font-weight)",
  h6_fontSize: "var(--mantine-h6-font-size)",
  h6_lineHeight: "var(--mantine-h6-line-height)",
  h6_fontWeight: "var(--mantine-h6-font-weight)",
});

export const smallerThan = stylex.defineConsts({
  xs: "@media (max-width: 36em)",
  sm: "@media (max-width: 48em)",
  md: "@media (max-width: 62em)",
  lg: "@media (max-width: 75em)",
  xl: "@media (max-width: 88em)",
});

export const largerThan = stylex.defineConsts({
  xs: "@media (min-width: 36em)",
  sm: "@media (min-width: 48em)",
  md: "@media (min-width: 62em)",
  lg: "@media (min-width: 75em)",
  xl: "@media (min-width: 88em)",
});
